---

- hosts: games
  become: true
  pre_tasks:
    - name: Do apt-get update with autoclean
      apt:
        update_cache: true
        autoclean: true
        cache_valid_time: 3600
      changed_when: false
  roles:
    - geerlingguy.pip
    - geerlingguy.docker
    - calvinbui.ansible_docker_network
    - linuxgsm
    - csgo
    - ddns
    - traefik

  post_tasks:
    - name: Start docker after drive is mounted
      lineinfile:
        path: /lib/systemd/system/docker.socket
        state: present
        insertafter: '^\[Unit\]$'
        line: "After=mnt-games.mount"

