---
- name: Plugins install
  copy:
    src: "files/{{ item.src }}/"
    dest: "{{ csgo_server_dir }}/serverfiles/csgo{{ item.dest }}"
    owner: "{{ common_user }}"
  loop:
    - src: Fortnite-Emotes-Extended
      dest: /
    - src: Quake_Sounds_v3
      dest: /
    - src: PTah
      dest: /
    - src: weapons
      dest: /
    - src: gloves
      dest: /
    - src: fortnite_hits
      dest: /
  notify: Update fastdl

- name: Plugin configs
  template:
    src: "{{ item.src }}"
    dest: "{{ csgo_server_dir }}/serverfiles/csgo{{ item.dest }}"
    owner: "{{ common_user }}"
  loop:
    - src: weapons.cfg.j2
      dest: /cfg/sourcemod/weapons.cfg
    - src: gloves.cfg.j2
      dest: /cfg/sourcemod/gloves.cfg
