---

- name: Create working dir
  file:
    path: "{{ csgo_server_dir }}"
    state: directory
    mode: '0755'
    owner: "{{ common_user }}"

- name: Download LinuxGSM
  get_url:
    url: https://linuxgsm.sh
    dest: "{{ csgo_server_dir }}/linuxgsm.sh"
    mode: '0755'
    owner: "{{ common_user }}"

- name: Create csgoserver from linuxgsm
  script: linuxgsm.sh
  args:
    executable: /bin/bash
    chdir: "{{ csgo_server_dir }}"
    creates: "{{ csgo_server_dir }}/csgoserver"

- name: Install csgoserver from linuxgsm
  script: csgoserver auto-install
  args:
    executable: /bin/bash
    chdir: "{{ csgo_server_dir }}"
    creates: "{{ csgo_server_dir }}/lgsm/config-lgsm/csgoserver/csgoserver.cfg"

- name: Generate fastdl
  script: csgoserver fast-dl
  args:
    executable: /bin/bash
    chdir: "{{ csgo_server_dir }}"
    creates: "{{ csgo_server_dir }}/public_html/fastdl/"

- name: Create CSGO FastDL Server
  docker_container:
    name: csgo-fastdl
    image: chauffer/nginx-autoindex
    state: started
    networks:
      - name: "{{ csgo_docker_network }}"
    purge_networks: true
    ports:
      - 8880:80
    volumes:
      - "{{ csgo_server_dir }}/public_html/:/usr/share/nginx/html:ro"
    restart_policy: always
  register: csgo_fastdl

- name: Install metamod by running ./csgoserver mod-install
  wait_for:
    path: "{{ csgo_server_dir }}/lgsm/mods/metamod-files.txt"
    state: present

- name: Install sourcemod by running ./csgoserver mod-install
  wait_for:
    path: "{{ csgo_server_dir }}/lgsm/mods/sourcemod-files.txt"
    state: present

- name: Template CSGO server configs
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ common_user }}"
  loop:
    - src: csgoserver.cfg.j2
      dest: "{{ csgo_server_dir }}/lgsm/config-lgsm/csgoserver/csgoserver.cfg"
    - src: server.cfg.j2
      dest: "{{ csgo_server_dir }}/serverfiles/csgo/cfg/csgoserver.cfg"
    - src: gamemode_casual.cfg.j2
      dest: "{{ csgo_server_dir }}/serverfiles/csgo/cfg/gamemode_casual.cfg"
    - src: gamemode_competitive.cfg.j2
      dest: "{{ csgo_server_dir }}/serverfiles/csgo/cfg/gamemode_competitive.cfg"
    - src: databases.cfg.j2
      dest: "{{ csgo_server_dir }}/serverfiles/csgo/addons/sourcemod/configs/databases.cfg"
    - src: core.cfg.j2
      dest: "{{ csgo_server_dir }}/serverfiles/csgo/addons/sourcemod/configs/core.cfg"

- name: Template service file
  template:
    src: csgoserver.service.j2
    dest: /etc/systemd/system/csgoserver.service
    mode: '0644'
    owner: root
    group: root

- name: Enable on boot
  systemd:
    name: csgoserver
    enabled: yes
    masked: no
    daemon_reload: yes
