---

- name: Create CSGO Web container
  docker_container:
    name: csgo
    image: catalysm/csgo-rankme:latest
    state: started
    networks:
      - name: "{{ csgo_docker_network }}"
    purge_networks: true
    ports:
      - 8888:8080
    env:
      MYSQL_USER: "root"
      MYSQL_DB: "{{ csgo_mysql_database }}"
      MYSQL_TABLE: "{{ csgo_mysql_database }}"
      MYSQL_HOST: "csgo-mysql.{{ csgo_docker_network }}"
      MYSQL_PASSWORD: "{{ csgo_mysql_root_password }}"
    restart_policy: always
  register: csgo_stats
