---

- name: Update fastdl
  shell: "./csgoserver fastdl"
  args:
    executable: /bin/bash
    chdir: "{{ csgo_server_dir }}"

- name: Restart CSGO Server
  service:
    name: csgoserver
    state: restarted
