---

- name: Create Traefik Container
  docker_container:
    name: traefik
    image: traefik:v2.0
    state: started
    command: --api.insecure=true --providers.docker --providers.docker.exposedByDefault=true --providers.docker.defaultRule="Host(`{% raw %}{{ .Name }}{% endraw %}.{{ ddns_zone }}`)" --providers.docker.useBindPortIP=true --accesslog=true
    networks: "{{ docker_networks }}"
    purge_networks: true
    ports:
      - 8080:8080
      - 443:443
      - 80:80
    env:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart_policy: always