---

- name: Install LinuxGSM dependencies
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - mailutils
    - postfix
    - curl
    - wget
    - file
    - tar
    - bzip2
    - gzip
    - unzip
    - bsdmainutils
    - python
    - util-linux
    - ca-certificates
    - binutils
    - bc
    - jq
    - tmux
    - lib32gcc1
    - libstdc++6
    - libstdc++6:i386
    - lib32z1
